name: Push

on:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.ref }}

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'shensven' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: shensven/hcetpd-sslvpn:latest
